### ISSUE TITLE
貌似跟jquery-ui有冲突 请问如何解决

### ISSUE THREAD

**Issue by kriestian** [tshi0912/city-picker#32]
貌似跟jquery-ui有冲突 请问如何解决

**Comment by tshi0912** [comment]
能否将冲突日志贴出？发自网易邮箱大师
            在2017年02月25日 13:06，kriestian 写道： 貌似跟jquery-ui有冲突 请问如何解决

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tshi0912/city-picker","title":"tshi0912/city-picker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tshi0912/city-picker"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"貌似跟jquery-ui有冲突 请问如何解决 (#32)"}],"action":{"name":"View Issue","url":"https://github.com/tshi0912/city-picker/issues/32"}}}
