### ISSUE TITLE
下拉的时候能只显示省份和城市两个tab么

### ISSUE THREAD

**Issue by zhangzhensheng** [tshi0912/city-picker#45]
现在有个需求，有的页面只需要省份和城市，有的省份、城市、区县都显示，有参数可以设置控制么，求助。。

**Comment by tshi0912** [comment]
使用level参数
发自网易邮箱大师
在2017年06月15日 20:43，zhangzhensheng 写道： Closed #45.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tshi0912/city-picker","title":"tshi0912/city-picker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tshi0912/city-picker"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #45."}],"action":{"name":"View Issue","url":"https://github.com/tshi0912/city-picker/issues/45#event-1125012780"}}}
